// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// The Prisma CLI does not read Next.js's `.env.local` on its own. Load it
// first (it wins, like Next.js), then fall back to `.env`. Real environment
// variables (e.g. Vercel) still take precedence — dotenv never overrides them.
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
